### PR TITLE
ENH: Better error messages

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes https://github.com/TomAugspurger/engarde/issues/7

This is a first attempt at some better error handling.
I don't really consider the exact error message to be
part of the public API, so don't rely on them.

Still need to do is_monotonic.
Need to protect against printing out massive arrays.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
cc @ianozsvald

Pretty rudimentary for now, but better than nothing.

```python
In [1]: from engarde.checks import none_missing

In [2]: df = pd.DataFrame({'A': [0, np.nan, -1, -2], 'B': [0, 2, -3, np.nan]})

In [3]: none_missing(df)
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
/Users/tom.augspurger/sandbox/engarde/engarde/checks.py in none_missing(df, columns)
     22     try:
---> 23         assert not df[columns].isnull().any().any()
     24     except AssertionError:

AssertionError:

During handling of the above exception, another exception occurred:

AssertionError                            Traceback (most recent call last)
<ipython-input-3-563ad7dea610> in <module>()
----> 1 none_missing(df)

/Users/tom.augspurger/sandbox/engarde/engarde/checks.py in none_missing(df, columns)
     27         bad = pd.Series(list(all_locs))[np.asarray(missing).ravel(1)]
     28         msg = bad.values
---> 29         raise AssertionError(msg)
     30     return df
     31

AssertionError: [(1, 'A') (3, 'B')]
```

I'm planning to cleanup the assertion reraise so there aren't nested AssertionErrors and the traceback will be cleaner.

**Comment by TomAugspurger** [comment]
Looks like

```python
except AssertionError as e:
    e.args += (info,)
    raise
```

Should work. Will update later today.

**Comment by ianozsvald** [comment]
Cool, will give the improvements a go, cheers!

**Comment by ianozsvald** [comment]
One comment - if there's a lot of failures (e.g. 200 rows in a dataframe with a None), you get a lot of debug output. Maybe truncate to a fixed character length in the output? Regardless this is an improvement, cheers!

**Pull request merged**
